<style type="text/css">
	.dataTables_filter {
	   display: none;
	}
</style>
         
<div class="row">
	<div class="col-md-12">
      	<div class="box box-success box-solid">
            <div class="box-header with-border">
              <h3 class="box-title" id="title_search">Enquêtes exploitant en attente de validation</h3>
            </div>
            <div class="box-body" id="table_ajax">
            	<div class="row">
            		<div class="col-md-4">
            			<div class="form-group">
            				<input type="text" width="195px" class="form-control" id="myInputTextField" placeholder="Recherche rapide">
            			</div>
            		</div>
            	</div>
        		<div class='table-responsive' id="div_table">
	            	<table class="table table-bordered table-stripped" id="tableExploitant">
	            		<thead>														<th>REFERENCE</th>														<th>DATE ENQUETE</th>
							<th>CODEEXPL</th>
	            			<th>NOM EXPLOITANT</th>
	            			<th>ADRESSE</th>
	            			<th>TELEPHONE</th>
	            			<th>VALEUR VENDUE</th>
	            		</thead>
	            		<tbody id="tbodyID">
	            		</tbody>
	            		
	            	</table>
	            </div>
            </div>
     	</div>
	</div>
</div>


<div id="retour_ajax"></div>


<script type="text/javascript">
	$("#div_table").hide();
	$("#div_tablecoll").hide();
	// oTable = $('#tableExploitant').DataTable();
	// $('#myInputTextField').keyup(function(){
	//       oTable.search($(this).val()).draw() ;
	
	// })
	$( document ).ready(function() {
	    load_data();
	});
	
	
	function load_data()
	{
		$("#title_search").html("");
		$("#title_search").html("<div class='overlay'><i class='fa fa-refresh fa-spin'></i></div>");
		$.ajax({
			url : "enqueteexplpend",
			type : "post",
			success : function($html){
				$("#btn-ajax").html("Recherche");
				$dataJSON = JSON.parse( $html );
				$jsonEncode = new Array();
				for(var i=0;i< $dataJSON.data.length; i++){
						
				        $jsonEncode.push({
						  'ref': $dataJSON.data[i].CODEQUEST,						  						  'date': $dataJSON.data[i].DATEENQ,
						  'codeexpl': $dataJSON.data[i].CODEEXPL,
				          'nom': $dataJSON.data[i].NOMEXPLOITANT,
				          'addresse': $dataJSON.data[i].ADRESSE,
				          'telephone': $dataJSON.data[i].NUMTEL,
				          'c12': $dataJSON.data[i].C12,
				          
				        })
							
				      }

				if ( $.fn.DataTable.isDataTable('#tableExploitant') ) {
				  $('#tableExploitant').DataTable().destroy();
				}

				$("#div_table").show();
				$("#div_table>table>tbody").html("");

				$testTable = $('#tableExploitant').DataTable( {
				        "data": $jsonEncode,
				        "scrollY": "500px",
				        "scrollCollapse": true,
				        "paging": false,
				        initComplete : function() {
				                $("#example_filter").detach().appendTo('#new-search-area');
				            },
				        "oLanguage": {
				            "sSearch": "Recheche: "
				          },
				        "columns": [
				            { "data": "ref" },														{ "data": "date" },
							{ "data": "codeexpl" },
							{ "data": "nom" },
				            { "data": "addresse" },
				            { "data": "telephone" },
				            { "data": "c12" }
				        ],
				        "order": [[ 0, "desc" ]]
				} );
				$('#myInputTextField').keyup(function(){
				   $testTable.search( $(this).val() ).draw();
				});

				$("#title_search").html("");
				$("#title_search").html("Enquêtes exploitant en attente de validation");

			},
			error : function($html){
				alert('Une erreur est survenue. Veuillez reéssayer.')
				$("#btn-ajax").html("Recherche");
				$("#retour_ajax").html('');
				$("#retour_ajax").html($html);
			}
		})
		
	}


</script>