<div class="col-md-10">
    <div class="box box-success box-solid">
        <div class="box-header with-border">
            <h3 class="box-title">Formulaire de validation</h3>
        </div>
        <div class="box-body">
        	<div class="form-group">
        	    <label for="inputEmail3" class="col-sm-4 control-label">Anarana (nom) :</label>
        	    <div class="col-sm-7">
        	    	<input type="text" class="form-control" id="operator_name" value="<?php echo $this->operateur["NOMEXPLOITANT"] ?>" />
        	    </div>
        	</div>  
        	<br>
        	<div class="form-group">
        	    <label for="inputEmail3" class="col-sm-4 control-label">Lahy/Vavy (sexe) :</label>
        	    <div class="col-sm-7">
        	    	<select class="form-control" id="operator_sexe">
        	    		<option value="1" <?php if($this->operateur["SEXE"] == "1") echo "selected"; ?> >Lahy (homme)</option>
        	    		<option value="2" <?php if($this->operateur["SEXE"] == "2") echo "selected"; ?> >Vavy (femme)</option>
        	    	</select>
        	    </div>
        	</div>
        	<br>
        	<div class="form-group">
        	    <label for="inputEmail3" class="col-sm-4 control-label">Taona (age) :</label>
        	    <div class="col-sm-7">
        	    	<input type="number" class="form-control" id="operator_age" value="<?php echo $this->operateur["AGE"] ?>" />
        	    </div>
        	</div>  
        	<br>
        	<div class="form-group">
        	    <label for="inputEmail3" class="col-sm-4 control-label">Fonenana (adresse) :</label>
        	    <div class="col-sm-7">
        	    	<input type="text" class="form-control" id="operator_adresse" value="<?php echo $this->operateur["ADRESSE"] ?>" />
        	    </div>
        	</div>
        	<br>
        	<div class="form-group">
        	    <label for="inputEmail3" class="col-sm-4 control-label">Kara-panondro (CIN) :</label>
        	    <div class="col-sm-7">
        	    	<input type="text" class="form-control" maxlength="12"  id="operator_cin"  value="<?php echo $this->operateur["NUMCIN"] ?>" />
        	    </div>
        	</div>
        	<br>
        	<div class="form-group">
        	    <label for="inputEmail3" class="col-sm-4 control-label">Toerana nanaovana ny kara-panondro (Lieu de délivrance CIN) :</label>
        	    <div class="col-sm-7">
        	    	<input type="text" class="form-control" id="operator_cin_lien" value="<?php echo $this->operateur["LIEUCIN"] ?>" />
        	    </div>
        	</div>
        	<br>
			<div class="form-group">
        	    &nbsp;
        	</div>
        	<div class="form-group">
        	    <label for="inputEmail3" class="col-sm-4 control-label">Asa atao (Type) :</label>
        	    <div class="col-sm-7">
        	    	<select class="form-control" id="operator_type">
        	    		<option value="1" <?php if($this->operateur["CODETYP"] == "1") echo "selected"; ?>>Mpitrandraka (exploitant)</option>
        	    		<option value="2" <?php if($this->operateur["CODETYP"] == "2") echo "selected"; ?>>Mpanangona (collecteur)</option>
        	    	</select>
        	    </div>
        	</div>
        	<br>
        	<div class="form-group">
        	    <label for="inputEmail3" class="col-sm-4 control-label">Laharan-ketra (NIF) - Tsy fenoina raha tsy misy :</label>
        	    <div class="col-sm-7">
        	    	<input type="text" class="form-control" id="operator_NIF" value="<?php echo $this->operateur["NIF"] ?>" />
        	    </div>
        	</div>
			<div class="form-group">
        	    &nbsp;
        	</div>						<br>
			<div class="form-group">
        	    <label for="inputEmail3" class="col-sm-4 control-label">Fifandraisana na Finday (contact) :</label>
        	    <div class="col-sm-7">
        	    	<input type="text" class="form-control" id="operator_contact"/>
        	    </div>
        	</div>
        	<!--iv class="form-group">
        	    <label for="inputEmail3" class="col-sm-4 control-label">Fokontany</label>
        	    <div class="col-sm-7">
        	    	<select class="form-control" id="fokontany_select">
        	    		<?php foreach ($this->fokontany as $keyFokontany => $valueFokontany) : ?>
        	    			<option value="<?php echo $valueFokontany['CODEFKT'] ?>" <?php if($this->operateur["CODEFKT"] == $valueFokontany['CODEFKT']) echo "selected"; ?> ><?php echo $valueFokontany['NOMFKT'] ?></option>
        	    		<?php endforeach ?>
        	    	</select>
        	    </div>
        	</div-->
        	<br>			<br>
			<div class="form-group">
				<div class="col-sm-7">
                    <button type="button" class="btn btn-danger btn-flat " onclick="sending_data(-1)">Esorina (Ne pas valider)</button>
					<button type="button" class="btn btn-success btn-flat " onclick="sending_data(1)">Ampidirina (Valider)</button>
				</div>
        	</div>
        	
        </div>
    </div>
</div>
<div id="retour_ajax"></div>	  
<script type="text/javascript">

	function security_form()
	{
		$("#operator_name").css("border-color","#d2d6de");
		$("#operator_age").css("border-color","#d2d6de");
		$("#operator_adresse").css("border-color","#d2d6de");
		$("#operator_cin").css("border-color","#d2d6de");
		$("#operator_cin_lien").css("border-color","#d2d6de");
		$("#operator_contact").css("border-color","#d2d6de");

		$name = $("#operator_name").val();
		$sexe = $("#operator_sexe").val();
		$age = $("#operator_age").val();
		$adresse = $("#operator_adresse").val();
		$cin = $("#operator_cin").val();
		$cin_lien = $("#operator_cin_lien").val();
		$type = $("#operator_type").val();
		$contact = $("#operator_contact").val();
		$nif = $("#operator_NIF").val();
		
		$valide = false

		if($name == "" || $sexe == "" || $age == "" || $adresse == "" || $cin == "" || $cin_lien == "" || $type == "")
		{
			if($name == "")
			{
				$("#operator_name").css("border-color","red");
			}
			if($age == "")
			{
				$("#operator_age").css("border-color","red");
			}
			if($adresse == "")
			{
				$("#operator_adresse").css("border-color","red");
			}
			if($cin == "")
			{
				$("#operator_cin").css("border-color","red");
			}
			if($cin_lien == "")
			{
				$("#operator_cin_lien").css("border-color","red");
			}
		}else{
			$valide = true;
		}
		return $valide;
	}

	function sending_data($validationNumb)
	{
		$name = $("#operator_name").val();
		$sexe = $("#operator_sexe").val();
		$age = $("#operator_age").val();
		$adresse = $("#operator_adresse").val();
		$cin = $("#operator_cin").val();
		$cin_lien = $("#operator_cin_lien").val();
		$type = $("#operator_type").val();
		$contact = $("#operator_contact").val();
		$nif = $("#operator_NIF").val();

		if(security_form())
		{
			if(confirm("Efa voamarina tsara daholo ve ireo rehetra ireo?"))
			{
				$.ajax({
					url : "validateoperator",
					type : "post",
					data : "CODEEXPL=<?php echo $this->operateur["CODEEXPL"] ?>&name="+$name+"&sexe="+$sexe+"&age="+$age+"&adresse="+$adresse+"&cin="+$cin+"&cin_lien="+$cin_lien+"&type="+$type+"&contact="+$contact+"&nif="+$nif+"&validation="+$validationNumb,
					success : function($retour){

						window.location = "index";

					},
					error : function($html){
						alert('Une erreur est survenue. Veuillez reéssayer.')
					}
				})
			}
		}else{
			alert("Veuillez vérifier votre formulaire.");
		}
	}

</script>


