<div class="col-md-10">

    <div class="box box-success box-solid">

        <div class="box-header with-border">

            <h3 class="box-title">Formulaire de ajout Agent communal</h3>

        </div>

        <div class="box-body">

          <div class="form-group">

              <label for="inputEmail3" class="col-sm-2 control-label">Nom :</label>

              <div class="col-sm-10">

                <input type="text" class="form-control" id="agent_name" />

              </div>

          </div> 
           <br> 
          <h4 class="text-center">Dans qu'elle</h4>
      
          <div class="form-group">

              <label for="inputEmail3" class="col-sm-2 control-label">Region :</label>

              <div class="col-sm-10">

                <select class="form-control" id="region" onchange="select_reg()">

                      <option value="" selected="true">----- REGION -----</option>

                      <?php foreach ($this->region as $keyRegion => $valueRegion) : ?>

                        <option value="<?php echo $valueRegion['CODEREG'] ?>"><?php echo $valueRegion['NOM_REG'] ?></option>
                        <!--option value="<?php echo $valueRegion['CODEREG'] ?>"><?php echo $valueRegion['NOM_REG'] .' - '.$valueRegion['CODEREG'] ?></option-->

                      <?php endforeach ?>

                    </select>

              </div>

          </div>

          <br>

          <div class="form-group">

              <label for="inputEmail3" class="col-sm-2 control-label">District  :</label>

              <div class="col-sm-10">

                <select class="form-control" id="district" onchange="select_dist()">

                      <option value="" selected="true">----- DISTRICT -----</option>

                       <?php foreach ($this->district as $keyDistrict => $valueDistrict) : ?>

                        <!--option value="<?php echo $valueDistrict['CODEDIST'] ?>" ><?php echo $valueDistrict['NOM_DIST'] ?></option>

                      <?php endforeach ?>--> 

                    </select>

              </div>

          </div>  

          <br>

          <div class="form-group">

              <label for="inputEmail3" class="col-sm-2 control-label">Commune :</label>

              <div class="col-sm-10">

                <select class="form-control" id="commune" onchange="select_comm()">

                      <option value="" selected="true">----- COMMUNE -----</option>

                      <?php foreach ($this->commune as $keyCommune => $valueCommune) : ?>

                        <!--option value="<?php echo $valueCommune['CODECOM'] ?>" ><?php echo $valueCommune['NOM_COMM'] ?></option-->

                      <?php endforeach ?>

                    </select>

              </div>

          </div>

          <br>

          <button type="button" class="btn  btn-flat " onclick="sending_data()">Valider</button>

        </div>

    </div>

</div>



<div id="retour_ajax"></div>

<script type="text/javascript">    

  function select_reg()

  {

    if($("#region").val() != "")

    {

      $.ajax({

        url : "filtredistrictbyregion",

        type : "post",

        data : "code="+$("#region").val(),

        success : function($option_html){



          $("#district").html("");

          $("#district").html($option_html);



        },

        error : function($html){

          alert('Une erreur est survenue. Veuillez reéssayer.')

        }

      })

    }

  } 



  function select_dist()

  {

    if($("#district").val() != "")

    {

      $.ajax({

        url : "filtrecommunebydistrict",

        type : "post",

        data : "code="+$("#district").val(),

        success : function($option_html){



          $("#commune").html("");

          $("#commune").html($option_html);



        },

        error : function($html){

          alert('Une erreur est survenue. Veuillez reéssayer.')

        }

      })

    }

  }
    function sending_data()

  {

    $name = $("#agent_name").val();

    $commune = $("#commune").val();

   
    if(security_form())

    {

      if(confirm("Confirmer l'enregistrement?"))

      {

        $.ajax({

          url : "insertagentcomm",

          type : "post",

          data : "name="+$name+"&commune="+$commune,

          success : function($retour){



            $("#retour_ajax").html("");

            $("#retour_ajax").html($retour);

            $("#agent_name").val("");

            $("#commune").val("");

          },

          error : function($html){

            alert('Une erreur est survenue. Veuillez reéssayer.')

          }

        })

      }

    }else{

      alert("Veuillez vérifier votre formulaire.");

    }

  }
</script>




