<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Observatoire</title>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <link rel="stylesheet" href="../public/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" href="../stylelog/style.css">
  <link rel="stylesheet" href="plugins/jvectormap/jquery-jvectormap-1.2.2.css">
  <link rel="stylesheet" href="../public/dist/css/AdminLTE.min.css">
  <link rel="stylesheet" href="../public/dist/css/skins/_all-skins.min.css">
  <script src="../plugins/jQuery/jQuery-2.2.0.min.js"></script>
</head>
<body class="hold-transition login-page">
<div class="container">
  <!--header-->
    <div class="jumbotron"> 
      <header>
        <div class="row">
          <div class="col-sm-12 align-top"> 
              <img src="../public/images/logo.png" class="img-responsive">
          </div>
        </div>
      </header>
    </div>
  
  <div>
    <!--div class="col-sm-8"-->
      <div class="login-box">
    
    <!-- /.login-logo -->
        <div class="login-box-body">
          <p class="login-box-msg">Ouvrir votre session</p>

          <form action="index/connexion" method="post">

            <div class="form-group has-feedback">
              <input type="text" class="form-control" placeholder="Login" name="user" required="true">
              <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
              <input type="password" class="form-control" placeholder="Mot de passe" name="mp" required="true">
              <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            </div>
            <div class="row">
              <div class="col-xs-8">
                <img src="../public/images/pagi.png" class="img-responsive">
              </div>
              <!-- /.col -->
              <div class="col-xs-4">
                <button type="submit" class="btn btn-primary btn-block btn-flat">Connecter</button>
              </div>
              <!-- /.col -->
            </div>
          </form>

        </div>
          
        <!-- /.login-box-body -->
      </div>
      <!-- /.login-box -->
    <!--/div-->
  </div>
</div><!--fin-container-->


<!-- jQuery 2.2.0 -->
<script src="../../public/plugins/jQuery/jQuery-2.2.0.min.js"></script>
<!-- Bootstrap 3.3.6 -->
<script src="../../public/bootstrap/js/bootstrap.min.js"></script>
<!-- iCheck -->
<script src="../../public/plugins/iCheck/icheck.min.js"></script>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' // optional
    });
  });
</script>
</body>
</html>
