<section class="content-header">
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-plus"></i> Observatoire</a></li>
        <li class="active">Géstion des produits</li>
      </ol>
</section>
<br>
<hr>
<div class="box box-success box-solid">
    <div class="box-header with-border">
      	<h3 class="box-title">Gestion des produits</h3>
    </div>
    <div class="box-body">
    	<table class="table table-striped table-bordered">
    		<thead>
    			<th>CODE PRODUIT</th>
    			<th>DESIGNATION</th>
    			<th>DETAILS</th>
    			<th>CLASS2</th>
    			<th></th>
    		</thead>
    		<tbody id="tbody_product">
    			<?php foreach ($this->product as $keyProduct => $valueProduct) : ?>
    				<tr>
    					<td><?php echo $valueProduct['CODPRODT'] ?></td>
    					<td><?php echo $valueProduct['DESIGNATION'] ?></td>
    					<td><?php echo $valueProduct['DETAILS'] ?></td>
    					<td><?php echo $valueProduct['CLASSE2'] ?></td>
    					<td></td>
    				</tr>
    			<?php endforeach ?>
    		</tbody>
    	</table>	
    	<br>
    	<button class="btn btn-success" id="btn_add" onclick="add_product()">Ajout</button>
    </div>
    
</div>

<div id="retour_ajax">
	
</div>
<script type="text/javascript">
	function add_product()
	{
		$html = "";
		$html += "<tr>";
		$html += "	<td><input type='text' id='product_code' ></td>";
		$html += "	<td><input type='text' id='product_designation' ></td>";
		$html += "	<td><input type='text' id='product_detail' ></td>";
		$html += "	<td><input type='text' id='product_class' ></td>";
		$html += "	<td><button class='btn btn-success' onclick='save_product()'>Enregistrer</button></td>";
		$html += "</tr>";

		$("#tbody_product").append($html);
		$("#btn_add").attr('disabled',true);
	}

	function security_form()
	{
		$valide = false;
		$product_code = $("#product_code");
		$product_designation =  $("#product_designation");
		$product_detail = $("#product_detail");
		$product_class = $("#product_class");

		$product_code.css("border-color","#d2d6de");
		$product_designation.css("border-color","#d2d6de");
		$product_detail.css("border-color","#d2d6de");
		$product_class.css("border-color","#d2d6de");

		if($product_code.val() == '' || $product_designation.val() == '' || $product_class.val() == '' )
		{
			if($product_code.val() == '')
			{
				$product_code.css("border-color","red");
			}
			if($product_designation.val() == '')
			{
				$product_designation.css("border-color","red");
			}
			if($product_class.val() == '')
			{
				$product_class.css("border-color","red");
			}
		}else{
			$valide =true;
		}
		return $valide;
	}

	function save_product()
	{
		$product_code_val = $("#product_code").val();
		$product_designation_val =  $("#product_designation").val();
		$product_detail_val = $("#product_detail").val();
		$product_class_val = $("#product_class").val();

		if(security_form())
		{
			if(confirm('Enregistrer ?'))
			{
				$.ajax({
					url : "insertproduct",
					type : "post",
					data : "code="+$product_code_val+"&designation="+$product_designation_val+"&detail="+$product_detail_val+"&class="+$product_class_val,
					success : function($retour){
						$("#tbody_product").html("");
						$("#tbody_product").html('<div class="overlay"><i class="fa fa-refresh fa-spin"></i></div>');
						$("#tbody_product").html("");
						$("#tbody_product").append($retour);
						$("#btn_add").attr('disabled',false);
					},
					error : function($html){
						alert('Une erreur est survenue. Veuillez reéssayer.')
					}
				})
			}
		}
	}

	function delete_product($code)
	{
		$.ajax({
			url : "deleteproduct",
			type : "post",
			data : "code="+$code,
			success : function($retour){
				$("#tbody_product").html("");
				$("#tbody_product").html('<div class="overlay"><i class="fa fa-refresh fa-spin"></i></div>');
				$("#tbody_product").html("");
				$("#tbody_product").append($retour);
			},
			error : function($html){
				alert('Une erreur est survenue. Veuillez reéssayer.')
			}
		})
	}
</script>